#! /bin/sh

sxhkd &

bspc monitor -d term web chat code music 6 7

bspc config border_width         0
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config super mod4
bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
#bspc config focus_follows_pointer true

bspc config presel_feedback_color \#aaaaaa

xsetroot -cursor_name left_ptr

feh --bg-scale ~/.config/misc/background.png
compton --config ~/.config/compton/compton.conf -b

$HOME/.config/polybar/launch.sh
